// ── COMPREHENSIVE SYSTEM CATALOG ──
// Every system, skill, tool, capability, agent, and workflow in the platform,
// categorized across the AI, business, and systematic world.
// status: "have" (green) | "partial" (yellow) | "gap" (red)

export const SYSTEM_CATALOG = [
  {
    id: "ai-intelligence",
    category: "AI & Intelligence Systems",
    icon: "Brain",
    items: [
      { name: "LLM Integration (InvokeLLM)", desc: "Multi-model LLM invocation with structured JSON output", capabilities: ["Text generation", "JSON mode", "File context", "Web search (Gemini)", "Model selection"], status: "have" },
      { name: "Vercel AI Gateway", desc: "External AI gateway for chat editing and page generation", capabilities: ["Chat completion", "Streaming", "Custom models", "Retry logic"], status: "have" },
      { name: "Autonomous Research Engine", desc: "Full industry research with rankings, strategies, and ROI analysis", capabilities: ["Industry ranking", "Strategy generation", "ROI simulation", "Domain scoring"], status: "have" },
      { name: "God Mode SEO AI", desc: "AI-powered SEO analysis and strategy generation", capabilities: ["SEO analysis", "Algorithm strategy", "Growth projection", "Domain recommendations"], status: "have" },
      { name: "AI Content Generation", desc: "Generate pages, social posts, and media via AI", capabilities: ["Page generation", "Social content", "Media generation", "Brand-aware"], status: "have" },
      { name: "AI Chat Editor", desc: "Chat-based visual website editing", capabilities: ["HTML editing", "Natural language", "Visual preview"], status: "have" },
      { name: "Autonomous Chat Agent", desc: "Floating AI agent with max autonomy for read/write/execute", capabilities: ["Entity CRUD", "Function invocation", "GPT sync", "Command parsing"], status: "partial" },
      { name: "Multi-Agent Orchestration", desc: "Coordinate multiple AI agents for complex tasks", capabilities: ["Agent swarms", "Task delegation", "Result aggregation"], status: "partial" },
      { name: "RAG / Vector Search", desc: "Retrieval-augmented generation with vector embeddings", capabilities: ["Embeddings", "Semantic search", "Context retrieval"], status: "gap" },
      { name: "AI Fine-tuning Pipeline", desc: "Custom model fine-tuning for domain-specific tasks", capabilities: ["Dataset prep", "Training runs", "Model evaluation"], status: "gap" },
      { name: "Computer Vision", desc: "Image analysis, OCR, and visual understanding", capabilities: ["OCR", "Object detection", "Image classification"], status: "gap" },
      { name: "AI Decision Engine", desc: "Rubric-based AI scoring and classification", capabilities: ["Classification", "Scoring", "Routing"], status: "partial" },
    ],
  },
  {
    id: "business-revenue",
    category: "Business & Revenue Systems",
    icon: "DollarSign",
    items: [
      { name: "Lead Generation", desc: "Capture and manage leads from forms and submissions", capabilities: ["Form capture", "Lead scoring", "Source tracking"], status: "have" },
      { name: "CRM (CrmContact)", desc: "Contact management with follow-up sequences", capabilities: ["Contact storage", "Follow-up scheduling", "Status tracking", "Calendar sync"], status: "have" },
      { name: "Outreach Campaigns", desc: "Email/SMS/MMS/WhatsApp outreach at scale", capabilities: ["Multi-channel", "Templates", "Batch sending", "Delivery tracking"], status: "have" },
      { name: "Catalog & Pricing", desc: "Product/service catalog with pricing", capabilities: ["Product catalog", "Pricing tiers", "Quote requests"], status: "have" },
      { name: "Commerce Orders", desc: "Order management with Stripe integration", capabilities: ["Order tracking", "Payment status", "Approval workflow"], status: "have" },
      { name: "Sales Pipeline", desc: "Visual sales pipeline with deal stages", capabilities: ["Deal stages", "Pipeline views", "Win/loss tracking"], status: "partial" },
      { name: "Subscription Billing", desc: "Recurring subscription management", capabilities: ["Plans", "Billing cycles", "Dunning"], status: "gap" },
      { name: "Affiliate System", desc: "Affiliate tracking and commission management", capabilities: ["Referral links", "Commission calc", "Payout tracking"], status: "gap" },
      { name: "Revenue Analytics", desc: "Revenue dashboards and forecasting", capabilities: ["MRR/ARR", "Churn analysis", "Forecasting"], status: "partial" },
      { name: "Customer Success", desc: "Customer health scoring and success tracking", capabilities: ["Health scores", "Onboarding tracking", "Renewal alerts"], status: "gap" },
    ],
  },
  {
    id: "data-storage",
    category: "Data & Storage Systems",
    icon: "Database",
    items: [
      { name: "Base44 Entity Database", desc: "32+ entities for all platform data", capabilities: ["CRUD", "Filtering", "Aggregation", "Realtime subscriptions"], status: "have" },
      { name: "Supabase Project A", desc: "Converged Supabase project A", capabilities: ["PostgreSQL", "Auth", "Storage", "Edge functions"], status: "partial" },
      { name: "Supabase Project B", desc: "Converged Supabase project B", capabilities: ["PostgreSQL", "Auth", "Storage", "Edge functions"], status: "partial" },
      { name: "Supabase Project C (Staging)", desc: "Converged Supabase staging project", capabilities: ["PostgreSQL", "Auth", "Storage", "Edge functions"], status: "partial" },
      { name: "Supabase Project D", desc: "Converged Supabase project D", capabilities: ["PostgreSQL", "Auth", "Storage", "Edge functions"], status: "partial" },
      { name: "Supabase Management API", desc: "Autonomous project creation and schema management", capabilities: ["Project creation", "Schema inspection", "SQL execution", "Secret management"], status: "have" },
      { name: "Realtime Sync", desc: "Live entity subscriptions for instant updates", capabilities: ["Create events", "Update events", "Delete events"], status: "have" },
      { name: "Multi-Tenant Isolation", desc: "Per-site data isolation architecture", capabilities: ["Tenant scoping", "Row-level security", "Per-site schemas"], status: "gap" },
      { name: "Data Warehouse", desc: "Centralized analytics warehouse", capabilities: ["ETL", "OLAP", "Reporting"], status: "gap" },
      { name: "Backup & Recovery", desc: "Automated backup and disaster recovery", capabilities: ["Scheduled backups", "Point-in-time recovery", "Restore testing"], status: "partial" },
    ],
  },
  {
    id: "automation-workflow",
    category: "Automation & Workflow Systems",
    icon: "Workflow",
    items: [
      { name: "Scheduled Workflows", desc: "Cron-based and interval-based automations", capabilities: ["Cron triggers", "Interval triggers", "One-time triggers"], status: "have" },
      { name: "Entity-Triggered Workflows", desc: "Automations fired on entity create/update/delete", capabilities: ["Create triggers", "Update triggers", "Delete triggers"], status: "have" },
      { name: "Connector-Triggered Workflows", desc: "Webhook-driven automations from external services", capabilities: ["Gmail webhooks", "Calendar webhooks", "Drive webhooks"], status: "have" },
      { name: "Multi-Step Workflows", desc: "Complex multi-step processes with branching", capabilities: ["Sequential steps", "Switch branching", "Data threading"], status: "have" },
      { name: "Durable Waits", desc: "Pause workflows for hours or days", capabilities: ["Time-based waits", "Condition-based waits", "Survives restarts"], status: "have" },
      { name: "Generation Queue Processor", desc: "Batch processing of page generation queue", capabilities: ["Batch processing", "Retry logic", "Queue draining"], status: "have" },
      { name: "Pack Approval Provisioning", desc: "Auto-provision packs when approved", capabilities: ["Approval trigger", "Auto-deploy", "Status tracking"], status: "have" },
      { name: "Social Media Auto-Generator", desc: "Automatically generates social content", capabilities: ["Content generation", "Scheduling", "Multi-platform"], status: "partial" },
      { name: "Daily Follow-Up Sequence", desc: "Automated daily follow-up for leads", capabilities: ["Email follow-up", "Schedule-based", "Status tracking"], status: "partial" },
      { name: "Human-in-the-Loop Gates", desc: "Approval gates within automated workflows", capabilities: ["Approval requests", "Manual review", "Conditional routing"], status: "partial" },
    ],
  },
  {
    id: "content-media",
    category: "Content & Media Systems",
    icon: "ImageIcon",
    items: [
      { name: "AI Page Generation", desc: "Generate SEO-optimized location/service pages", capabilities: ["HTML generation", "Compliance scoring", "Batch creation"], status: "have" },
      { name: "AI Image Generation", desc: "Generate images from text prompts", capabilities: ["Text-to-image", "Style reference", "Brand assets"], status: "have" },
      { name: "AI Video Generation", desc: "Generate videos from text prompts", capabilities: ["Text-to-video", "6-8 second clips", "Audio track"], status: "have" },
      { name: "AI Speech Generation", desc: "Text-to-speech with multiple voices", capabilities: ["Multiple voices", "Multilingual", "MP3 output"], status: "have" },
      { name: "Social Content Generation", desc: "Generate social media posts and calendars", capabilities: ["30-day calendars", "Multi-platform", "Trending templates"], status: "have" },
      { name: "Media Asset Management", desc: "Store and manage generated media", capabilities: ["Asset storage", "Campaign linking", "Platform tagging"], status: "have" },
      { name: "Content Variation Engine", desc: "Spin unique content for millions of pages", capabilities: ["Content spinning", "Uniqueness scoring", "Bulk generation"], status: "gap" },
      { name: "Brand Design System", desc: "Consistent brand tokens across generated sites", capabilities: ["Color tokens", "Typography", "Component library"], status: "partial" },
      { name: "Video Script Generation", desc: "AI-generated video scripts for social", capabilities: ["Script templates", "Hook generation", "CTA optimization"], status: "have" },
    ],
  },
  {
    id: "seo-search",
    category: "SEO & Search Systems",
    icon: "Search",
    items: [
      { name: "Programmatic SEO Engine", desc: "Generate 1000s of location/service pages", capabilities: ["Batch generation", "Location targeting", "Service targeting", "Compliance rules"], status: "have" },
      { name: "God Mode SEO", desc: "Full SEO analysis and strategy", capabilities: ["Industry analysis", "Algorithm strategy", "Growth projection", "Domain scoring"], status: "have" },
      { name: "Google Compliance Rules", desc: "Programmatic SEO rules based on Google guidelines", capabilities: ["Content rules", "Technical rules", "Structure rules", "Local rules"], status: "have" },
      { name: "NearMe Domain Strategy", desc: "NearMe/NearYou domain scoring and availability", capabilities: ["Domain scoring", "Availability check", "Demand scoring"], status: "have" },
      { name: "Digital Dominance Discovery", desc: "Find directory, review, and citation targets", capabilities: ["Directory targets", "Review platforms", "Citation sources"], status: "have" },
      { name: "AEO Optimization", desc: "Answer Engine Optimization for AI search", capabilities: ["FAQ schema", "Answer formatting", "AI-readable content"], status: "partial" },
      { name: "GEO Optimization", desc: "Generative Engine Optimization", capabilities: ["Entity-based content", "Knowledge graph", "AI citations"], status: "partial" },
      { name: "Schema Markup Automation", desc: "Auto-generate structured data markup", capabilities: ["JSON-LD", "Schema types", "Validation"], status: "partial" },
      { name: "Google Search Console", desc: "Indexation tracking and performance monitoring", capabilities: ["Index status", "Query tracking", "Sitemap submission"], status: "gap" },
      { name: "Google Business Profile", desc: "Local SEO via Google Business Profile", capabilities: ["Profile management", "Review responses", "Posting"], status: "gap" },
      { name: "Backlink Automation", desc: "Automated backlink building and monitoring", capabilities: ["Link building", "Backlink monitoring", "Disavow management"], status: "gap" },
      { name: "Local Citation Builder", desc: "Automated citation building across directories", capabilities: ["NAP consistency", "Directory submission", "Citation tracking"], status: "gap" },
      { name: "Review Management", desc: "Automated review generation and response", capabilities: ["Review requests", "AI responses", "Rating monitoring"], status: "gap" },
    ],
  },
  {
    id: "social-media",
    category: "Social Media Systems",
    icon: "Share2",
    items: [
      { name: "Social Content Library", desc: "Browse and manage generated social posts", capabilities: ["Content browsing", "Platform filters", "Category filters"], status: "have" },
      { name: "Post Scheduling", desc: "Schedule posts across platforms", capabilities: ["Time scheduling", "Platform targeting", "Calendar view"], status: "have" },
      { name: "Social Account Management", desc: "Manage connected social accounts", capabilities: ["Account storage", "Platform tracking", "Status management"], status: "have" },
      { name: "30-Day Content Calendar", desc: "AI-generated 30-day multi-platform calendars", capabilities: ["Multi-platform", "Trending topics", "Batch generation"], status: "have" },
      { name: "Auto-Posting to Platforms", desc: "Direct API posting to social platforms", capabilities: ["Facebook API", "Instagram API", "Twitter API", "LinkedIn API"], status: "gap" },
      { name: "AI Comment Engagement", desc: "AI reads and replies to social comments", capabilities: ["Comment monitoring", "AI responses", "Sentiment analysis"], status: "gap" },
      { name: "AI DM Responses", desc: "AI responds to direct messages", capabilities: ["DM monitoring", "AI replies", "Lead qualification"], status: "gap" },
      { name: "Social Analytics", desc: "Performance tracking across platforms", capabilities: ["Engagement metrics", "Reach tracking", "Conversion attribution"], status: "gap" },
      { name: "Influencer Outreach", desc: "Automated influencer discovery and outreach", capabilities: ["Influencer discovery", "Outreach automation", "Relationship tracking"], status: "gap" },
    ],
  },
  {
    id: "deployment-infra",
    category: "Deployment & Infrastructure",
    icon: "Server",
    items: [
      { name: "Railway Deployment", desc: "Deploy services to Railway hosting", capabilities: ["Service creation", "Environment config", "URL management"], status: "have" },
      { name: "Vercel Deployment", desc: "Deploy frontends to Vercel", capabilities: ["Project creation", "Domain config", "Auto-deploy"], status: "have" },
      { name: "Supabase Provisioning", desc: "Create and manage Supabase projects", capabilities: ["Project creation", "Schema management", "Secret management"], status: "have" },
      { name: "GoDaddy Domain API", desc: "Domain registration and management via GoDaddy", capabilities: ["Domain search", "Registration", "DNS management"], status: "have" },
      { name: "Provisioning Jobs", desc: "Track deployment jobs across providers", capabilities: ["Job tracking", "Multi-provider", "Status monitoring"], status: "have" },
      { name: "Pack Provisioning", desc: "Auto-provision approved packs to hosting", capabilities: ["Approval trigger", "Auto-deploy", "Domain config"], status: "have" },
      { name: "Bulk Site Deployment", desc: "Deploy 1000s of sites in bulk", capabilities: ["Batch deploy", "Template replication", "Domain assignment"], status: "partial" },
      { name: "Domain Auto-Purchase", desc: "Automatically purchase domains for new sites", capabilities: ["Availability check", "Auto-purchase", "DNS setup"], status: "gap" },
      { name: "CI/CD Pipeline", desc: "Continuous integration and deployment", capabilities: ["Auto-build", "Test runs", "Auto-deploy"], status: "gap" },
      { name: "System Monitoring", desc: "Health monitoring and alerting", capabilities: ["Uptime monitoring", "Error tracking", "Alerts"], status: "partial" },
      { name: "Cloud Browser Service", desc: "Headless browser for scraping and automation", capabilities: ["Headless browsing", "Form filling", "Screenshot capture"], status: "partial" },
    ],
  },
  {
    id: "communication-outreach",
    category: "Communication & Outreach",
    icon: "Send",
    items: [
      { name: "Email (SendEmail + Resend)", desc: "Send emails via platform and Resend", capabilities: ["Template emails", "Plain text", "Attachments", "Custom domain"], status: "have" },
      { name: "SMS (Telnyx)", desc: "Send SMS messages via Telnyx", capabilities: ["SMS sending", "Number management", "Delivery tracking"], status: "have" },
      { name: "MMS (Telnyx)", desc: "Send MMS with media via Telnyx", capabilities: ["Media attachments", "Image messaging"], status: "have" },
      { name: "WhatsApp Messaging", desc: "Send WhatsApp messages", capabilities: ["Text messages", "Media messages", "Template messages"], status: "partial" },
      { name: "Google Calendar Integration", desc: "Calendar events and scheduling", capabilities: ["Event creation", "Event reading", "Webhook triggers"], status: "have" },
      { name: "Gmail Integration", desc: "Read and send Gmail", capabilities: ["Email reading", "Email sending", "Webhook triggers"], status: "have" },
      { name: "Daily Follow-Up Automation", desc: "Automated follow-up sequences for leads", capabilities: ["Schedule-based", "Multi-step", "Status tracking"], status: "partial" },
      { name: "Push Notifications", desc: "Mobile push notifications", capabilities: ["iOS push", "Android push", "Action URLs"], status: "have" },
    ],
  },
  {
    id: "analytics-testing",
    category: "Analytics & Testing",
    icon: "BarChart3",
    items: [
      { name: "A/B Testing", desc: "Split testing for headlines, CTAs, layouts", capabilities: ["Variant tracking", "Conversion tracking", "Confidence scoring", "Winner selection"], status: "have" },
      { name: "Custom Event Tracking", desc: "Track custom analytics events", capabilities: ["Event tracking", "Property tracking", "User analytics"], status: "have" },
      { name: "Traffic Analytics", desc: "Website traffic and visitor analytics", capabilities: ["Page views", "Visitor tracking", "Source attribution"], status: "gap" },
      { name: "Conversion Tracking", desc: "Track conversions and funnels", capabilities: ["Funnel analysis", "Conversion events", "Attribution"], status: "partial" },
      { name: "Heatmaps", desc: "Visual heatmaps of user interactions", capabilities: ["Click tracking", "Scroll tracking", "Visual overlay"], status: "gap" },
      { name: "Session Recording", desc: "Record user sessions for analysis", capabilities: ["Session replay", "Interaction tracking", "Funnel visualization"], status: "gap" },
      { name: "Cohort Analysis", desc: "User cohort retention analysis", capabilities: ["Cohort grouping", "Retention curves", "Behavior analysis"], status: "gap" },
    ],
  },
  {
    id: "agent-autonomous",
    category: "Agent & Autonomous Systems",
    icon: "Bot",
    items: [
      { name: "Agent Entity", desc: "Store autonomous AI agent definitions", capabilities: ["Agent storage", "Type classification", "Status tracking", "Config management"], status: "have" },
      { name: "Agent Task Execution", desc: "Execute tasks assigned to agents", capabilities: ["Task dispatch", "Result tracking", "Error handling"], status: "have" },
      { name: "Swarm Generation", desc: "Generate agent swarms from patterns", capabilities: ["Pattern-based swarms", "Role assignment", "Governance rules"], status: "have" },
      { name: "Form Filler Agent", desc: "Autonomous form-filling agent", capabilities: ["Form detection", "Field mapping", "Auto-submit"], status: "partial" },
      { name: "Poster Agent", desc: "Autonomous content posting agent", capabilities: ["Content posting", "Platform targeting", "Schedule-based"], status: "partial" },
      { name: "Scraper Agent", desc: "Autonomous web scraping agent", capabilities: ["Page scraping", "Data extraction", "Rate limiting"], status: "partial" },
      { name: "Headless Browser Agent", desc: "Full headless browser automation", capabilities: ["Page navigation", "Screenshot capture", "Form interaction"], status: "partial" },
      { name: "Orchestrator Agent", desc: "Master agent that coordinates other agents", capabilities: ["Task delegation", "Result aggregation", "Workflow coordination"], status: "partial" },
      { name: "GPT-Commanded Agent", desc: "Agent that receives commands from external GPT", capabilities: ["GPT sync", "Command parsing", "Read/write/execute"], status: "partial" },
    ],
  },
  {
    id: "integration-connector",
    category: "Integration & Connector Systems",
    icon: "Plug",
    items: [
      { name: "Google Calendar", desc: "Calendar events and scheduling", capabilities: ["Event CRUD", "Webhook triggers"], status: "have" },
      { name: "Gmail", desc: "Email reading and sending", capabilities: ["Email CRUD", "Webhook triggers"], status: "have" },
      { name: "Google Drive", desc: "File storage and management", capabilities: ["File CRUD", "Webhook triggers"], status: "have" },
      { name: "Google Docs", desc: "Document creation and editing", capabilities: ["Doc CRUD", "Content editing"], status: "have" },
      { name: "Google Sheets", desc: "Spreadsheet data management", capabilities: ["Sheet CRUD", "Data read/write"], status: "have" },
      { name: "Google Tasks", desc: "Task management", capabilities: ["Task CRUD", "List management"], status: "have" },
      { name: "GitHub", desc: "Repository management and code sync", capabilities: ["Repo CRUD", "Code sync", "PR management"], status: "have" },
      { name: "Supabase", desc: "Database and backend provisioning", capabilities: ["Project CRUD", "Schema management", "SQL execution"], status: "have" },
      { name: "HubSpot", desc: "CRM and marketing automation", capabilities: ["Contact sync", "Deal tracking", "Marketing automation"], status: "have" },
      { name: "Slack", desc: "Team communication and notifications", capabilities: ["Message sending", "Channel management"], status: "gap" },
      { name: "Notion", desc: "Documentation and knowledge base", capabilities: ["Page CRUD", "Database sync"], status: "gap" },
      { name: "Salesforce", desc: "Enterprise CRM", capabilities: ["Lead sync", "Opportunity tracking", "Custom objects"], status: "gap" },
      { name: "Stripe", desc: "Payment processing", capabilities: ["Checkout", "Subscriptions", "Webhooks"], status: "gap" },
      { name: "Facebook/Instagram API", desc: "Social media posting and management", capabilities: ["Post creation", "Story management", "Insights"], status: "gap" },
      { name: "Twitter/X API", desc: "Twitter posting and management", capabilities: ["Tweet creation", "Timeline reading", "Engagement"], status: "gap" },
      { name: "LinkedIn API", desc: "LinkedIn posting and management", capabilities: ["Post creation", "Profile management", "Analytics"], status: "gap" },
      { name: "TikTok API", desc: "TikTok content management", capabilities: ["Video upload", "Analytics", "Content scheduling"], status: "gap" },
      { name: "Webhook System", desc: "Inbound webhook handling for external services", capabilities: ["Endpoint exposure", "Signature validation", "Event routing"], status: "partial" },
    ],
  },
  {
    id: "intelligence-knowledge",
    category: "Intelligence & Knowledge Systems",
    icon: "Lightbulb",
    items: [
      { name: "Opportunity Tracking", desc: "Market opportunities and demand themes", capabilities: ["Opportunity storage", "Demand scoring", "Theme tracking"], status: "have" },
      { name: "Product Benchmarking", desc: "Benchmark products with value scores", capabilities: ["Value scoring", "Build speed", "Recurring revenue", "Margin tracking"], status: "have" },
      { name: "Info Category Rankings", desc: "Information category value rankings", capabilities: ["Category ranking", "Value scoring", "User targeting"], status: "have" },
      { name: "Demand Theme Analysis", desc: "High-signal demand themes by domain", capabilities: ["Theme discovery", "Buyer identification", "Product form mapping"], status: "have" },
      { name: "Buyer Persona Profiles", desc: "Buyer personas with channels and behaviors", capabilities: ["Persona storage", "Channel mapping", "Behavior tracking"], status: "have" },
      { name: "Problem Pattern Library", desc: "Problem patterns by domain with metrics", capabilities: ["Pattern storage", "Metric tracking", "Domain mapping"], status: "have" },
      { name: "Discovery Methods", desc: "Methods for discovering money-making opportunities", capabilities: ["Method catalog", "Automation patterns", "Cadence tracking"], status: "have" },
      { name: "Contractor Personas", desc: "Contractor profiles with AI adoption metrics", capabilities: ["Persona modeling", "Adoption probability", "Hours saved tracking"], status: "have" },
      { name: "Prompt Library", desc: "Reusable AI prompt collection", capabilities: ["Prompt storage", "Category tagging", "Use case tracking"], status: "have" },
      { name: "Workflow Pack Library", desc: "Workflow state machine definitions", capabilities: ["State machines", "Evidence types", "Human gates"], status: "have" },
      { name: "Connector Catalog", desc: "Integration connector reference catalog", capabilities: ["Connector listing", "Capability tracking"], status: "have" },
    ],
  },
];

// ── AGENT CATALOG (potential + existing agent types) ──
export const AGENT_CATALOG = [
  { name: "Research Agent", agent_type: "scraper", desc: "Autonomously researches industries, competitors, and market opportunities", capabilities: ["Web scraping", "Data extraction", "Industry analysis", "Competitor research", "Market sizing"], skills: ["Search", "Scrape", "Analyze", "Report"], category: "Intelligence" },
  { name: "SEO Strategist Agent", agent_type: "form_filler", desc: "Generates and executes SEO strategies including God Mode analysis", capabilities: ["SEO analysis", "Keyword research", "Content strategy", "Schema markup", "Rank tracking"], skills: ["Analyze", "Strategize", "Optimize", "Report"], category: "SEO" },
  { name: "Content Writer Agent", agent_type: "form_filler", desc: "Generates SEO-optimized content for pages, posts, and media", capabilities: ["Page generation", "Blog writing", "Social content", "Content spinning", "Brand voice"], skills: ["Write", "Edit", "Optimize", "Spin"], category: "Content" },
  { name: "Social Media Manager Agent", agent_type: "poster", desc: "Manages social media content creation, scheduling, and posting", capabilities: ["Content creation", "Post scheduling", "Multi-platform", "Engagement tracking", "Trend monitoring"], skills: ["Create", "Schedule", "Post", "Engage"], category: "Social Media" },
  { name: "Image Generator Agent", agent_type: "form_filler", desc: "Generates images, graphics, and visual assets via AI", capabilities: ["Image generation", "Brand assets", "Social graphics", "Ad creatives", "Logo design"], skills: ["Generate", "Edit", "Brand", "Compose"], category: "Media" },
  { name: "Video Producer Agent", agent_type: "form_filler", desc: "Generates video content and scripts for social and ads", capabilities: ["Video generation", "Script writing", "Trend analysis", "Multi-format"], skills: ["Script", "Generate", "Edit", "Publish"], category: "Media" },
  { name: "Deployment Agent", agent_type: "headless_browser", desc: "Provisions and deploys websites to Railway, Vercel, and Supabase", capabilities: ["Site deployment", "Domain config", "DNS setup", "SSL management", "Health monitoring"], skills: ["Provision", "Deploy", "Configure", "Monitor"], category: "Infrastructure" },
  { name: "Domain Hunter Agent", agent_type: "scraper", desc: "Finds, scores, and purchases available domains", capabilities: ["Domain search", "Availability check", "Demand scoring", "Auto-purchase", "DNS config"], skills: ["Search", "Score", "Purchase", "Configure"], category: "Infrastructure" },
  { name: "Lead Engagement Agent", agent_type: "poster", desc: "Engages with leads via email, SMS, and social DMs", capabilities: ["Email outreach", "SMS campaigns", "DM responses", "Follow-up sequences", "Lead qualification"], skills: ["Outreach", "Follow-up", "Qualify", "Convert"], category: "Sales" },
  { name: "Comment Responder Agent", agent_type: "poster", desc: "AI that reads and replies to social media comments", capabilities: ["Comment monitoring", "AI responses", "Sentiment analysis", "Engagement boosting"], skills: ["Monitor", "Analyze", "Respond", "Engage"], category: "Social Media" },
  { name: "Review Manager Agent", agent_type: "poster", desc: "Generates and responds to customer reviews", capabilities: ["Review requests", "AI responses", "Rating monitoring", "Reputation management"], skills: ["Request", "Respond", "Monitor", "Manage"], category: "Reputation" },
  { name: "Citation Builder Agent", agent_type: "form_filler", desc: "Builds local citations across directories", capabilities: ["NAP consistency", "Directory submission", "Citation tracking", "Duplicate detection"], skills: ["Submit", "Track", "Verify", "Report"], category: "SEO" },
  { name: "Backlink Builder Agent", agent_type: "scraper", desc: "Builds and monitors backlinks", capabilities: ["Link prospecting", "Outreach automation", "Backlink monitoring", "Disavow management"], skills: ["Prospect", "Outreach", "Monitor", "Report"], category: "SEO" },
  { name: "Analytics Agent", agent_type: "scraper", desc: "Tracks and reports on traffic, conversions, and performance", capabilities: ["Traffic analysis", "Conversion tracking", "Funnel analysis", "Report generation"], skills: ["Track", "Analyze", "Report", "Optimize"], category: "Analytics" },
  { name: "Orchestrator Agent", agent_type: "form_filler", desc: "Master agent that coordinates all other agents", capabilities: ["Task delegation", "Agent coordination", "Result aggregation", "Workflow management"], skills: ["Delegate", "Coordinate", "Aggregate", "Decide"], category: "Orchestration" },
  { name: "GPT Sync Agent", agent_type: "form_filler", desc: "Receives commands from external GPT and executes them", capabilities: ["GPT communication", "Command parsing", "Entity CRUD", "Function invocation", "Full autonomy"], skills: ["Sync", "Parse", "Execute", "Report"], category: "Orchestration" },
  { name: "Form Filler Agent", agent_type: "form_filler", desc: "Autonomously fills out forms across the web", capabilities: ["Form detection", "Field mapping", "Auto-submit", "Captcha handling"], skills: ["Detect", "Map", "Fill", "Submit"], category: "Automation" },
  { name: "Scraper Agent", agent_type: "scraper", desc: "Scrapes websites for data extraction", capabilities: ["Page scraping", "Data extraction", "Rate limiting", "Proxy rotation"], skills: ["Scrape", "Extract", "Parse", "Store"], category: "Automation" },
];

// ── SYSTEM REQUIREMENTS (for gap analysis) ──
export const SYSTEM_REQUIREMENTS = [
  {
    category: "Core Platform",
    requirements: [
      { name: "Entity Database (32+ entities)", status: "have", desc: "All data entities for the platform" },
      { name: "Backend Functions (17+ functions)", status: "have", desc: "All backend operations and integrations" },
      { name: "Automated Workflows (5 workflows)", status: "have", desc: "Scheduled and triggered automations" },
      { name: "Connected Integrations (9 connectors)", status: "have", desc: "Google Suite, GitHub, Supabase, HubSpot" },
      { name: "Admin UI (25+ pages)", status: "have", desc: "Full admin interface with sidebar navigation" },
    ],
  },
  {
    category: "Supabase Convergence",
    requirements: [
      { name: "Project A Connection", status: "partial", desc: "Secrets configured, schema inspection needed" },
      { name: "Project B Connection", status: "partial", desc: "Secrets configured, schema inspection needed" },
      { name: "Project C (Staging) Connection", status: "partial", desc: "Secrets configured, staging environment" },
      { name: "Project D Connection", status: "partial", desc: "Secrets configured, schema inspection needed" },
      { name: "Supabase Management API", status: "have", desc: "Autonomous project creation and schema management" },
      { name: "Adapter Mapping (canonical ↔ legacy)", status: "gap", desc: "Map canonical identifiers to legacy table names" },
      { name: "Cross-Project Data Sync", status: "gap", desc: "Synchronize data across all 4 projects" },
    ],
  },
  {
    category: "Per-Site Architecture",
    requirements: [
      { name: "Per-Site Admin Portal", status: "gap", desc: "Standard admin portal template per site" },
      { name: "Per-Site Client Portal", status: "gap", desc: "Business owner operating system per site" },
      { name: "Per-Site AI Chat Agent", status: "partial", desc: "Autonomous chat agent per site" },
      { name: "Per-Site Super Agents", status: "partial", desc: "Autonomous agents per site" },
      { name: "Per-Site Secret Management", status: "gap", desc: "Per-site secret vault for API keys" },
      { name: "Multi-Tenant Data Isolation", status: "gap", desc: "Per-site data isolation architecture" },
    ],
  },
  {
    category: "Autonomous Operations",
    requirements: [
      { name: "Autonomous Chat Agent (Floating)", status: "partial", desc: "Floating AI agent with max autonomy" },
      { name: "GPT Command Channel", status: "partial", desc: "GPT can command the chat agent" },
      { name: "Read/Write/Execute Permissions", status: "partial", desc: "Granular autonomy controls" },
      { name: "Agent Enable/Disable Controls", status: "partial", desc: "Toggle agents into action" },
      { name: "Bulk Site Deployment Pipeline", status: "partial", desc: "Auto-deploy 1000s of sites" },
      { name: "Content Variation Engine", status: "gap", desc: "Unique content for millions of pages" },
    ],
  },
  {
    category: "Social Media Automation",
    requirements: [
      { name: "Content Generation", status: "have", desc: "AI social content generation" },
      { name: "Post Scheduling", status: "have", desc: "Schedule posts across platforms" },
      { name: "Auto-Posting to Platforms", status: "gap", desc: "Direct API posting (FB, IG, TW, LI, TT)" },
      { name: "AI Comment Engagement", status: "gap", desc: "AI reads and replies to comments" },
      { name: "AI DM Responses", status: "gap", desc: "AI responds to direct messages" },
    ],
  },
  {
    category: "SEO / AEO / GEO",
    requirements: [
      { name: "Programmatic SEO Engine", status: "have", desc: "Batch page generation" },
      { name: "God Mode SEO", status: "have", desc: "Full SEO analysis" },
      { name: "AEO Optimization Module", status: "partial", desc: "Answer Engine Optimization" },
      { name: "GEO Optimization Module", status: "partial", desc: "Generative Engine Optimization" },
      { name: "Google Search Console", status: "gap", desc: "Indexation tracking" },
      { name: "Google Business Profile", status: "gap", desc: "Local SEO automation" },
      { name: "Backlink Automation", status: "gap", desc: "Automated backlink building" },
      { name: "Local Citation Builder", status: "gap", desc: "Automated citation building" },
      { name: "Review Management", status: "gap", desc: "Automated review generation/response" },
    ],
  },
  {
    category: "Scale Infrastructure",
    requirements: [
      { name: "Bulk Site Deployment", status: "partial", desc: "Deploy 1000s of sites" },
      { name: "Domain Auto-Purchase", status: "gap", desc: "Auto-buy domains via GoDaddy" },
      { name: "Per-Site Analytics", status: "gap", desc: "Traffic and performance per site" },
      { name: "Per-Site CRM", status: "gap", desc: "Lead management per site" },
      { name: "Per-Site Booking", status: "gap", desc: "Appointment scheduling per site" },
      { name: "Per-Site Email Marketing", status: "gap", desc: "Automated email sequences per site" },
      { name: "Per-Site SMS Marketing", status: "gap", desc: "SMS marketing via Telnyx per site" },
    ],
  },
];