const ROOT = 'https://media.base44.com/files/public/6ac74a836169b94bd04cf453/';
export const TEMPLATE_AUDIT = [
  { name: 'XTREME Code Base', file: '2e53da4b0_xtreme-code-base.zip', files: 103, functions: 0, agents: 0, workflows: 0, sha256: 'e48ee3cae5476facdaa1f5803e45f10d8bb0a9f37e397f6b45304d8da4b1a493', stage: 'Build asset routing', status: 'mapped_not_installed', evidence: 'src/pages/Arsenal.jsx; base44/entities/Asset.jsonc', finding: 'Asset, prompt and package registries. Not an autonomous coding runtime; no backend functions or workers are included.' },
  { name: 'Marketplace Template', file: '10dd99011_marketplace-1.zip', files: 175, functions: 11, agents: 0, workflows: 0, sha256: 'ddb4b93b06f59e01308a2a3b07129a0560cf5a082bbdd673b0ee2d3034002010', stage: 'Independent release validation', status: 'mapped_not_installed', evidence: 'src/components/handoff/KNOWN_GAPS.md', finding: 'Source documents model-estimated audit scores, an optimizer that does not apply fixes, payment defects and missing concurrency boundaries. Quarantined from automatic release; validation/approval contracts are adapted, not its claimed PASS results.' },
  { name: 'Video Shot', file: '529c08e67_video-shot-copy-ca7742a9.zip', files: 89, functions: 0, agents: 0, workflows: 0, sha256: 'ba2f0e887cc29e2ef08c563e2715304206d09c9f2f4d9befdd31442efd8fbcf9', stage: 'Social video production', status: 'blocked_mock_generator', evidence: 'src/components/IntroGenerator.jsx: handleGenerate', finding: 'Generation only waits 2.5 seconds and displays success. No generated video, render worker or publishing integration. Its success screen is NOT imported as working video generation.' },
  { name: 'Business Portfolio', file: '0d8916b70_business-portfolio-copy-e3ee2141.zip', files: 85, functions: 0, agents: 0, workflows: 0, sha256: '5814ef74e913e5acd743f6eb04c0ee96ca85b29c5f77130fff8ffd3b35408c02', stage: 'Website concepts', status: 'composition_adapted', evidence: 'src/pages/Home.jsx: HeroSection → AboutSection → WorkSection → ContactSection', finding: 'Portfolio composition is adapted into the portfolio concept renderer with generated business-specific copy. The source is a presentation template, not a website factory.' },
  { name: 'Blueprint Local', file: 'fadfc7831_blueprint-local-copy-5884d4f9.zip', files: 100, functions: 0, agents: 0, workflows: 0, sha256: 'f2c9158fcfc918fbd20c6de1e4362559707ddd0111413f8e6f8e113dddeb98f5', stage: 'Local-service website concepts', status: 'composition_adapted', evidence: 'src/components/sections/CommandHero.jsx; src/pages/Home.jsx', finding: 'Split command hero, service matrix and local CTA composition are adapted into the local-service concept renderer. Original invented/local-only business claims are not copied.' },
  { name: 'Code Gen AI', file: '5820f51dc_code-gen-ai-copy-017472eb.zip', files: 89, functions: 0, agents: 0, workflows: 0, sha256: '0d9cc53f0379a3404ce5ee8e1eaa2a4b9734535c55cd2a4d0e8b50767af93b92', stage: 'AI-assisted vision / future coding worker', status: 'mapped_requires_adapter', evidence: 'src/pages/Assistant.jsx: @/entities/Conversation; @/integrations/Core', finding: 'Legacy imports refer to Conversation and client InvokeLLM, but no matching backend schema is included. Assistant purpose is served by the connected vision assistant; autonomous code execution is not installed.' },
  { name: 'Digital Creators Vault', file: '02df9bcde_digital-creators-vault-copy-bc5f32bf.zip', files: 310, functions: 29, agents: 1, workflows: 2, sha256: '961d7e0b7eb9c19531f833b15e97b8c3d02d85f70686c55b8020cb41a4fa8e3a', stage: 'Commerce / client and admin portals', status: 'mapped_requires_adapter', evidence: 'base44/functions/createCheckoutSession/entry.ts; base44/agents/store_assistant.jsonc', finding: 'Storefront, Stripe checkout, orders, downloads and memberships need destination entity mapping, payment installation and scoped permissions. Neither payment handlers nor imported agents are activated blindly.' }
].map(t => ({ ...t, url: ROOT + t.file, audited_at: '2026-10-09', verification: 'source_inspection_not_live_acceptance' }));
export const SYSTEM_AUDIT = [
  { area: 'Phase 1 · Research', finding: 'Old skip-trace inferred information from an AI prompt; web research discarded provider evidence. The connected pipeline now stores business-only research, source links and source-checked quotations.', state: 'core_repaired' },
  { area: 'Phase 2 · God Mode', finding: 'Missing values were replaced with 300,000 searches, $15 CPC and $1,000 customer value. Random draws were unseeded, demand multiplied with page count, domain cost counted twice, and monthly charts used cumulative values. Fallbacks removed and numerical engine corrected.', state: 'core_repaired' },
  { area: 'Phase 3 · Builder', finding: 'Prior answers were omitted from the website blueprint; approvals did not bind an immutable design. The new pipeline saves hashed stage artifacts, 10 concepts, approval identity and draft pages using the selected concept.', state: 'core_repaired' },
  { area: 'Quick Access · Templates', finding: 'Stored ZIPs are not installed applications. Seven new attachments are individually inspected and mapped; the other 42 catalog entries have inventory review only, not full source acceptance.', state: 'partial_audit' },
  { area: 'Launch & Scale', finding: 'A queued page is not deployed, indexed or ranked. Independent release checks, live infrastructure receipts, distinct useful local content, budget ceilings and queue concurrency need a separate release implementation.', state: 'release_locked' },
  { area: 'Social, Communications & Agents', finding: 'Content plans are not published media. Social account permissions, actual video rendering, outbound consent/unsubscribe handling, voice configuration, scoped agent tools and measured optimization loops are not completed by this core build.', state: 'not_enabled' }
];