import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import SocialPostCard from "@/components/social/SocialPostCard";
import { Share2, Calendar, Clock, Sparkles, Loader2 } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

const categories = ["all", "promotional", "educational", "engagement", "behind_scenes", "testimonial", "announcement", "other"];
const platforms = ["all", "facebook", "instagram", "twitter", "linkedin", "tiktok", "youtube"];

export default function SocialMediaLibrary() {
  const [posts, setPosts] = useState([]);
  const [schedules, setSchedules] = useState([]);
  const [loading, setLoading] = useState(true);
  const [category, setCategory] = useState("all");
  const [platform, setPlatform] = useState("all");
  const [showGen, setShowGen] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [genTopic, setGenTopic] = useState("");
  const [genPlatform, setGenPlatform] = useState("all");
  const [genCount, setGenCount] = useState(3);

  const handleGenerate = async () => {
    if (!genTopic) return;
    setGenerating(true);
    try {
      await base44.functions.invoke("generateSocialContent", {
        topic: genTopic, platform: genPlatform, count: genCount,
        category: category !== "all" ? category : "promotional",
      });
      setGenTopic(""); setShowGen(false);
      const query = {};
      if (category !== "all") query.category = category;
      if (platform !== "all") query.platform = platform;
      const { items } = await base44.entities.SocialPost.filter(query, { sort: "-created_date", limit: 50 });
      setPosts(items || []);
    } catch (e) { console.error(e); }
    finally { setGenerating(false); }
  };

  useEffect(() => {
    async function load() {
      setLoading(true);
      try {
        const query = {};
        if (category !== "all") query.category = category;
        if (platform !== "all") query.platform = platform;
        const [postsPage, schedulesPage] = await Promise.all([
          base44.entities.SocialPost.filter(query, { sort: "-created_date", limit: 50 }),
          base44.entities.PostSchedule.filter({ active: true }, { sort: "-created_date", limit: 50 }),
        ]);
        setPosts(postsPage.items || []);
        setSchedules(schedulesPage.items || []);
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [category, platform]);

  return (
    <div className="p-8">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold mb-1">Social Media Library</h1>
          <p className="text-muted-foreground">AI-generated content, categorized and scheduled across platforms</p>
        </div>
        <Button onClick={() => setShowGen(true)}>
          <Sparkles className="w-4 h-4" />
          Generate Posts
        </Button>
      </div>

      <div className="flex gap-3 mb-6">
        <Select value={category} onValueChange={setCategory}>
          <SelectTrigger className="w-44">
            <SelectValue placeholder="Category" />
          </SelectTrigger>
          <SelectContent>
            {categories.map((cat) => (
              <SelectItem key={cat} value={cat} className="capitalize">
                {cat === "all" ? "All Categories" : cat.replace("_", " ")}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select value={platform} onValueChange={setPlatform}>
          <SelectTrigger className="w-40">
            <SelectValue placeholder="Platform" />
          </SelectTrigger>
          <SelectContent>
            {platforms.map((p) => (
              <SelectItem key={p} value={p} className="capitalize">
                {p === "all" ? "All Platforms" : p}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-20">
          <div className="w-8 h-8 border-4 border-muted border-t-foreground rounded-full animate-spin" />
        </div>
      ) : posts.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <Share2 className="w-12 h-12 text-muted-foreground mb-4" />
          <h3 className="font-semibold mb-1">No posts yet</h3>
          <p className="text-sm text-muted-foreground">Content generated by ChatGPT will appear here</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
          {posts.map((post) => (
            <SocialPostCard key={post.id} post={post} />
          ))}
        </div>
      )}

      {schedules.length > 0 && (
        <div className="mt-10">
          <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
            <Calendar className="w-5 h-5" />
            Posting Schedule
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {schedules.map((s) => (
              <Card key={s.id}>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm flex items-center justify-between">
                    <span className="capitalize">{s.category}</span>
                    <span className="capitalize text-muted-foreground font-normal">{s.platform}</span>
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-xs text-muted-foreground flex items-center gap-1.5">
                    <Clock className="w-3 h-3" />
                    <span className="capitalize">{s.day_of_week}</span> at {s.time_of_day}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      )}

      <Dialog open={showGen} onOpenChange={setShowGen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Generate Social Posts</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div>
              <Label>Topic</Label>
              <Input value={genTopic} onChange={(e) => setGenTopic(e.target.value)} placeholder="e.g. roof maintenance tips for winter" />
            </div>
            <div>
              <Label>Platform</Label>
              <Select value={genPlatform} onValueChange={setGenPlatform}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {platforms.map((p) => (
                    <SelectItem key={p} value={p} className="capitalize">{p === "all" ? "All Platforms" : p}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>Number of Posts</Label>
              <Input type="number" min="1" max="10" value={genCount} onChange={(e) => setGenCount(parseInt(e.target.value) || 3)} />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowGen(false)}>Cancel</Button>
            <Button onClick={handleGenerate} disabled={generating || !genTopic}>
              {generating ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Sparkles className="w-4 h-4 mr-2" />}
              {generating ? "Generating..." : "Generate"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}